syntax = "proto3";

package recommendation;

option go_package = "github.com/elpomoika/mediahub/recommendation/protos/gen/go/recommendation;recommendation";

message GetSimilarMoviesRequest {
  int64 movie_id = 1;
  repeated int64 genre_ids = 2;
}

// отдаем только id найденного медиа
message SimilarMovie {
  int64 movie_id = 1;
}

message GetSimilarMoviesResponse {
  repeated SimilarMovie movies = 1;
}

message AddMovieRequest {
  int64 movie_id = 1;
  repeated int64 genre_ids = 2;
}

message AddMovieResponse {
  bool success = 1;
}

service RecommendationService {
  rpc GetSimilarMovies(GetSimilarMoviesRequest) returns (GetSimilarMoviesResponse);

  rpc AddMovie(AddMovieRequest) returns (AddMovieResponse);
}
